[package]
name = "rusty-git"
version = "0.1.0"
authors = ["Youssef-Shehata"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["derive"] }
flate2 = "1.0"
hex = "0.4.3"
hex-literal = "0.4.1"
sha1 = "0.10.6"

